/**
 * Parses HTML content and extracts Apache ECharts chart blocks.
 * Chart blocks are typically generated by pyecharts or similar tools and contain:
 * - Script tags loading echarts library and themes
 * - Style for the chart container
 * - Div with id="chart-xxx"
 * - Inline script with echarts.init() and setOption()
 */

export type ContentSegment =
  | { type: "html"; html: string }
  | { type: "echarts"; chartHtml: string };

/**
 * Detects if the given HTML string contains an ECharts chart block.
 * Matches pyecharts/Apache ECharts output: script(s) + style + div + init script.
 * Supports: (1) Simple chart with empty div, (2) India map with wrap/hint/chart div structure.
 * Supports echarts.apache.org, assets.pyecharts.org, and common CDNs.
 */
const ECHARTS_BLOCK_REGEX =
  /((?:<script[^>]*\ssrc="[^"]*(?:echarts|pyecharts)[^"]*"[^>]*><\/script>\s*)*(?:<script[^>]*\ssrc="[^"]*(?:themes?|assets|theme)[^"]*"[^>]*><\/script>\s*)?)?<style[^>]*>[\s\S]*?#chart-[\w-]+[\s\S]*?<\/style>\s*(?:<div\s+id="chart-[\w-]+-wrap"[^>]*>\s*(?:<div\s+id="chart-[\w-]+-hint"[^>]*>[\s\S]*?<\/div>\s*)?<div\s+id="chart-[\w-]+"[^>]*>\s*<\/div>\s*<\/div>|<div\s+id="chart-[\w-]+"[^>]*>\s*<\/div>)\s*<script>[\s\S]*?echarts\.init[\s\S]*?(?:\.setOption|applyOption)[\s\S]*?<\/script>/gi;

/**
 * Parses HTML content and returns an array of segments (html or echarts).
 * ECharts blocks are extracted and returned as separate segments; the rest is sanitized HTML.
 */
const DEBUG_ECHARTS =
  (typeof import.meta !== "undefined" &&
    (import.meta as { env?: { DEV?: boolean } }).env?.DEV) ||
  (typeof process !== "undefined" && process.env?.NODE_ENV === "development");

export function parseHtmlWithEcharts(html: string): ContentSegment[] {
  const raw = html || "";
  if (!raw.trim()) return [{ type: "html", html: "" }];

  const segments: ContentSegment[] = [];
  let lastIndex = 0;

  const regex = new RegExp(ECHARTS_BLOCK_REGEX.source, "gi");
  let match: RegExpExecArray | null;
  let matchCount = 0;

  while ((match = regex.exec(raw)) !== null) {
    matchCount++;
    const chartHtml = match[0];
    const matchStart = match.index;

    if (matchStart > lastIndex) {
      const htmlBefore = raw.slice(lastIndex, matchStart);
      if (htmlBefore.trim()) {
        segments.push({ type: "html", html: htmlBefore });
      }
    }

    segments.push({ type: "echarts", chartHtml });
    lastIndex = regex.lastIndex;
  }

  if (lastIndex < raw.length) {
    const htmlAfter = raw.slice(lastIndex);
    if (htmlAfter.trim()) {
      segments.push({ type: "html", html: htmlAfter });
    }
  }

  if (segments.length === 0) {
    if (DEBUG_ECHARTS && raw.includes("echarts")) {
      console.warn(
        "[echartsParser] No ECharts block matched (echarts found in html). Raw length:",
        raw.length,
      );
    }
    return [{ type: "html", html: raw }];
  }

  if (DEBUG_ECHARTS && matchCount > 0) {
    console.log("[echartsParser] Matched", matchCount, "ECharts block(s)");
  }
  return segments;
}

/**
 * Checks if the given HTML contains any ECharts chart blocks.
 */
export function hasEchartsContent(html: string): boolean {
  const r = new RegExp(ECHARTS_BLOCK_REGEX.source, "i");
  return r.test(html || "");
}

const CHART_HEIGHT_REGEX = /height:\s*(\d+)px/i;
const CHART_WIDTH_REGEX = /width:\s*(\d+)px/i;

/**
 * Extracts the intended chart height from the chart HTML (from backend style block).
 * Returns the parsed height in px, or null if not found.
 */
export function extractChartHeight(chartHtml: string): number | null {
  const m = (chartHtml || "").match(CHART_HEIGHT_REGEX);
  if (!m || !m[1]) return null;
  const h = parseInt(m[1], 10);
  return Number.isFinite(h) && h > 0 ? h : null;
}

/**
 * Extracts the intended chart width from the chart HTML (from backend InitOpts).
 * Returns the parsed width in px, or null if not found.
 */
export function extractChartWidth(chartHtml: string): number | null {
  const m = (chartHtml || "").match(CHART_WIDTH_REGEX);
  if (!m || !m[1]) return null;
  const w = parseInt(m[1], 10);
  return Number.isFinite(w) && w > 0 ? w : null;
}
